name: Build Manager on push

on: push

permissions:
  packages: write

jobs:
  build:
    name: Build image
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set env variables
        run: |
          echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV
          REPO_OWNER="${{ github.repository_owner }}""
          echo "REPO_OWNER=${REPO_OWNER,,}" >> $GITHUB_ENV


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        id: qemu

      - name: Setup Docker buildx action
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Run Docker buildx
        run: |
                docker buildx build \
                --platform linux/amd64,linux/arm64 \
                --cache-from "type=local,src=/tmp/.buildx-cache" \
                --cache-to "type=local,dest=/tmp/.buildx-cache" \
                --tag ghcr.io/$REPO_OWNER/manager:$BRANCH \
                --output "type=registry" ./packages/manager/
